# Generated by Django 5.2.10 on 2026-01-10 21:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_lecturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='blocks',
        ),
        migrations.AlterUniqueTogether(
            name='studentscore',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentscore',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentscore',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='subjects',
        ),
        migrations.AddField(
            model_name='student',
            name='foreign_language_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='core.course')),
                ('homeroom_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classes', to='core.lecturer')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.classroom'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudentExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('math', models.FloatField(blank=True, null=True)),
                ('literature', models.FloatField(blank=True, null=True)),
                ('foreign_language', models.FloatField(blank=True, null=True)),
                ('physics', models.FloatField(blank=True, null=True)),
                ('chemistry', models.FloatField(blank=True, null=True)),
                ('biology', models.FloatField(blank=True, null=True)),
                ('history', models.FloatField(blank=True, null=True)),
                ('geography', models.FloatField(blank=True, null=True)),
                ('civic_education', models.FloatField(blank=True, null=True)),
                ('foreign_language_code', models.CharField(blank=True, max_length=5, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_score', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ExamBlock',
        ),
        migrations.DeleteModel(
            name='StudentScore',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
