# Generated by Django 5.2.10 on 2026-01-12 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_subject_blocks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamresult',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_results', to='core.course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Quản trị viên'), ('Lecturer', 'Giảng viên'), ('Student', 'Học sinh')], default='Student', max_length=20),
        ),
    ]
