"""
Django settings for GScore project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import cloudinary
import os
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.templatetags.static import static
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-eid-2s-$5zpu7&-y&b35kd6&^51pi^zp6y)k0odzr=ja-5%r*6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

USE_TZ = False
TIME_ZONE = "Asia/Ho_Chi_Minh"


# Application definition

INSTALLED_APPS = [ 
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'rest_framework',
    'drf_yasg',
    'oauth2_provider',
    'core',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'GScore.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'GScore.wsgi.application'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'g_score',
        'USER': 'root',
        'PASSWORD': 'VuTrongTin12092004@',
        'HOST': 'localhost', 
        "PORT":'3306'
    }
}


AUTH_USER_MODEL='core.User'

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_I18N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static", 
]

STATIC_ROOT = BASE_DIR / "staticfiles" 
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ROOT_URLCONF = 'GScore.urls'

FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800
USE_I18N = True

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "oauth2_provider.contrib.rest_framework.OAuth2Authentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

OAUTH2_PROVIDER = {
    "SCOPES": {"read": "Read scope", "write": "Write scope"},
    "ACCESS_TOKEN_EXPIRE_SECONDS": 3600,
    "GRANT_TYPES": ["password", "refresh_token", "authorization_code"],
}


cloudinary.config(
    cloud_name=os.getenv("CLOUNDINARY_NAME"),
    api_key=os.getenv("CLOUDINARY_API_KEY"),
    api_secret=os.getenv("CLOUDINARY_API_SECRET"),
    secure=True,
)

UNFOLD = {
    "SITE_TITLE": "GScore Admin",
    "SITE_HEADER": "GScore",
    "SITE_URL": "/",
    "SITE_ICON": None,
    "SIDEBAR": {
        "navigation": [
             {
                "title": _("Token Manager"),
                "icon": "token",
                "items": [
                    {
                        "title": _("Token Manager"),
                        "icon": "token",
                        "link": reverse_lazy("gscore_admin:index"),
                    },
                ],
            },
            {
                "title": _("Home"),
                "icon": "home",
                "items": [
                    {
                        "title": _("Dashboard"),
                        "icon": "dashboard",
                        "link": reverse_lazy("gscore_admin:index"),
                    },
                ],
            },
             {
                "title": _("User Manager"),
                "separator": True,
                "items": [
                    {
                        "icon": "person",
                        "title": _("Users"),
                        "link": reverse_lazy("gscore_admin:core_user_changelist")
                    },
                ]
            },
              {
                "title": _("Course Manage"),
                "separator": True,
                "items": [
                    {
                        "title": _("Course"),
                        "icon": "assignment",
                        "link": reverse_lazy("gscore_admin:core_course_changelist"),
                    },
                ],
            },
            
            {
                "title": _("Score Attributes"),
                "separator": True,
                "items": [
                    {
                        "title": _("Import Student Exam Results"),
                        "icon": "upload",
                        "link": reverse_lazy("gscore_admin:core_studentexamresult_import"),
                    },
                    {
                        "title": _("Student Exam Results"),
                        "icon": "school",
                        "link": reverse_lazy("gscore_admin:core_studentexamresult_changelist"),
                    },
                ],
            },
             {
                "title": _("Score Statistics"),
                "separator": True,
                "items": [
                    {
                        "title": _("Statistics Score"),
                        "icon": "insert_chart",
                        "link": reverse_lazy("gscore_admin:core_studentexamresult_statistics"),
                    },
                ],
            }
        ],
        
    },
    "STYLES": [
        lambda request: static("css/styles.css"),
    ],
    "COLORS": {
        "base": {
            "50": "249 250 251",
            "100": "243 244 246",
            "200": "229 231 235",
            "300": "209 213 219",
            "400": "156 163 175",
            "500": "107 114 128",
            "600": "75 85 99",
            "700": "55 65 81",
            "800": "31 41 55",
            "900": "17 24 39",
            "950": "3 7 18",
        },
        "primary": {
            "50": "250 245 255",
            "100": "206 250 254",
            "200": "162 244 253",
            "300": "83 234 253",
            "400": "0 211 242",
            "500": "0 184 219",
            "600": "0 146 184",
            "700": "0 117 149",
            "800": "0 95 120",
            "900": "16 78 100",
            "950": "5 51 69",
        },
    },
}